name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        ls
    - name: Install Fastapi
      run: |
        pip install fastapi
        # install uvicorn
        pip install "uvicorn[standard]"
    - name: Install Requests
      run: |
        pip install requests
    - name: Install Docker
      run: |
        sudo apt-get remove docker docker-engine docker.io containerd runc -y
        sudo apt-get update
        sudo apt-get install \
              ca-certificates \
              curl \
              gnupg \
              lsb-release \
              git -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg 
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io -y
    - name: Install Requests
      run: |
        git clone https://github.com/tianrking/dont_post_me.git
        uvicorn jin10.a:app --reload
  
  

              
        
        
   
